# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Fatalement bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser tweepy pytz
        
    - name: Publish tweet
      run: |
        import feedparser
        from datetime import datetime, timedelta
        import tweepy
        import pytz

        def _tweet_article(api, article):
            text = f"I wrote a new article called '{article.title}'! \nYou can read it {article.link}"
            print(f'will tweet about {article.title}')
            api.update_status(text)


        def get_articles():
            previous_hour = datetime.today().replace(tzinfo=pytz.utc) - timedelta(hours=96)
            feed_url = "https://fatalement.com/feed.xml"
            blog_feed = feedparser.parse(feed_url)

            auth = tweepy.OAuthHandler("${{ secrets.CONSUMER_KEY }}", "${{ secrets.CONSUMER_SECRET }}")
            auth.set_access_token("${{ secrets.ACCESS_TOKEN }}", "${{ secrets.ACCESS_TOKEN_SECRET }}")
            api = tweepy.API(auth)


            for article in blog_feed.entries:
                article_date = datetime.strptime(article.published, '%a, %d %b %Y %H:%M:%S %z')
                if article_date >= previous_hour:
                    _tweet_article(api, article)
            print('----- END -----')

